### PR TITLE
Multiple closure serializers - With opis/closure support

### LINKED ISSUE #49: `SuperClosure\SerializerInterface` is deprecated.
**Description**
When I implement the readme example of `Serializing Closures` on PHP 8.1.12, I get this ErrorException.

> SuperClosure\SerializableClosure implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary)

Does it need to change the depency of `SuperClosure` to `Opis Closure` (Maybe the superClosure repo is no longer maintained) to support the closures requirement?

Thanks.

### PR DESCRIPTION
**Pull request by jrbasso**
Closes #49

### CODE REVIEW

File: src/JsonSerializer/JsonSerializer.php [hunk 1]
```diff
@@ -49,11 +49,9 @@ class JsonSerializer
     protected $objectMappingIndex = 0;
 
     /**
-     * Closure serializer instance
-     *
-     * @var ClosureSerializerInterface
+     * Closure manager
```
Comment (cjsaylor) [inline src/JsonSerializer/JsonSerializer.php:52]: @jrbasso Shouldn't this be typed to `ClosureSerializerManager`?

File: src/JsonSerializer/ClosureSerializer/ClosureSerializerManager.php [hunk 2]
```diff
@@ -0,0 +1,61 @@
...
+
+        foreach ($this->preferred as $preferred) {
+            if (isset($this->closureSerializer[$preferred])) {
+                return $this->closureSerializer[$preferred];
+            }
+        }
+        return current($this->closureSerializer);
+    }
+
+    public function getSerializer(string $classname)
```
Comment (cjsaylor) [inline src/JsonSerializer/ClosureSerializer/ClosureSerializerManager.php:54]: @jrbasso Should docblock this to know that it can return a nullable since it doesn't throw when not found.

**Review by cjsaylor — CHANGES_REQUESTED** [review]

File: src/JsonSerializer/JsonSerializer.php (hunk 1 above)
Comment (jrbasso) [reply src/JsonSerializer/JsonSerializer.php:52]: @cjsaylor Just fixed it.

**Review by cjsaylor — APPROVED** [review]
